resolver 127.0.0.11 valid=5s ipv6=off;

server {
  listen 80;
  server_name _;

  location / {
    set $app_backend http://app:8080;
    proxy_pass $app_backend;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
